Import("env")

env = env.Clone()

env.InjectThirdPartyIncludePaths(libraries=['wiredtiger'])

env.Library(
    target='s3_wt',
    source=[
        'blockstore_fs.cpp',
        's3_wt_init.cpp',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/serveronly',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/db/storage/kv/kv_storage_engine',
        '$BUILD_DIR/mongo/db/storage/storage_engine_metadata',
        '$BUILD_DIR/mongo/db/storage/wiredtiger/storage_wiredtiger',
        '$BUILD_DIR/mongo/db/storage/wiredtiger/storage_wiredtiger_core',
    ],
)
